### PR TITLE
Call refactored variable methods with this._game instead of game

### PR DESCRIPTION
**Pull request by vcarluer**
Hi, i'm trying to get a game for ludum dare with Belle so it's maybe not the best fix i'm a bit on a hurry.
Variables doesn't work anymore, at least on Windows last version.
I hope this is a good solution for you or lead you to code one, variables are so important!

### CODE REVIEW

**Comment by vcarluer** [comment]
Error in falseActions init; actions was pushed in trueActions so there were no way to branch correctly.

**Comment by fr33mind** [comment]
I see, what a stupid mistake, sorry. I'll release a 0.5.1a today since i've found many small annoying bugs in the past weeks. Thanks for the help.

**Comment by vcarluer** [comment]
I had to do a really dirty correction too to continue my game: code
generated by modify variable action calls game.getValue which does not
exist. game is the div and it is getVariableValue. I tried a jQuery proxy
in  game.js but did not worked and no time so I've done one in
Addvariable... I will give you link to my Ludum dare entry done with belle
if I have time to finish (not sure now)

**Comment by fr33mind** [comment]
One of the problems you mention i've fixed in 15 Feb (after 0.5a release) but the other is still there.
I wasn't aware people were already doing stuff like this, that's why i wasn't much concerned in testing every single aspect before a release, but yea, i need to be more careful from now on.
Anyway good luck and i hope you finish your game. If you need any help please contact me again, i'll be available for the next hours.

**Comment by vcarluer** [comment]
Had to picj object.js from source because of problem in state image in
Windows version.
Let's continue ! ;p

2015-04-19 18:17 GMT+02:00 fr33mind <notifications@github.com>:

**Comment by vcarluer** [comment]
Hello,

You proposed me some help.
I cannot achieved to find a bug in firefox: it does not load sounds.
It works locally.
If you have time can you telle me if you have an idea of the bug please ?
Here the game : there is a version without sounds for firefox:
http://ludumdare.com/compo/ludum-dare-32/?action=preview&uid=11818

Thanks.

Vincent

2015-04-19 23:11 GMT+02:00 Vincent Carluer <vcarluer@gmail.com>:

**Comment by fr33mind** [comment]
Yes, no problem. I've found the issue, the solution is simple, check commit acab4d14fb78653ae06a554eff2b516685c515c5.

**Comment by vcarluer** [comment]
Thank you very much it is working well in firefox now too :D
As said in the game page i am not really proud of the game I made (lack of
time and skills merely) but I am glad to have use your tool Belle, learned
a lot on Visual Novel game design.

2015-04-20 20:46 GMT+02:00 fr33mind <notifications@github.com>:

**Pull request merged**
